# syntax = docker/dockerfile:experimental

FROM library/node:lts-bullseye as ui-builder

WORKDIR /app
COPY ./ui/ ./
RUN  npm install && npm run build


FROM docker-registry.schwanzer.online/dockerhub_proxy/snowgoons/rustbuilder:rustc-1.69.0 as builder

USER root

WORKDIR /app/src


#ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

RUN rm -rf /app/src/static/*||true
COPY --from=ui-builder /app/dist /app/src/static
RUN rm -rf /app/src/target/release/deps/podfetch*
RUN rm -rf /app/src/target/release/podfetch*

ADD Cargo.toml .
ADD static ./static
ADD migrations ./migrations
ADD src ./src
ADD build.rs .
ADD .git .
ADD db ./db
RUN cargo update
RUN rustup target add armv7-unknown-linux-musleabihf
RUN --security=insecure mkdir -p /usr/local/cargo/registry/index && \
    chmod 777 /usr/local/cargo/registry/index && \
    mount -t tmpfs none /usr/local/cargo/registry/index && \
    RUSTFLAGS='-C target-feature=-crt-static' cargo build --target armv7-unknown-linux-musleabihf --release


FROM library/alpine:3.17 AS Runtime
WORKDIR /app/
RUN apk add libgcc tzdata
ENV TZ=Europe/Berlin

COPY --from=builder /app/src/target/release/podfetch /app/podfetch
COPY --from=builder /app/src/migrations /app/migrations
COPY --from=builder /app/src/db /app/db
COPY --from=ui-builder /app/dist /app/static
COPY ./docs/default.jpg /app/static/default.jpg


EXPOSE 8000
CMD ["./podfetch"]