FROM talk.schwanzer.online/dockerhub_proxy/library/node:alpine as ui-builder

WORKDIR /app
COPY ./ui/ ./
RUN  npm install && npm run build


FROM talk.schwanzer.online/dockerhub_proxy/library/rust:alpine3.17 as dependency-cache
USER root

RUN apk add pkgconfig openssl-dev libc-dev
WORKDIR /app/src

ADD Cargo.toml .
ADD dummy.rs ./src/main.rs
RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release


FROM talk.schwanzer.online/dockerhub_proxy/library/rust:alpine3.17 as builder

USER root

WORKDIR /app/src

RUN apk add pkgconfig openssl-dev libc-dev


COPY --from=dependency-cache /usr/local/cargo /usr/local/cargo
COPY --from=dependency-cache /app/src/target/ /app/src/target/

RUN rm -rf /app/src/target/release/deps/podgrabv2*
RUN rm -rf /app/src/target/release/podgrabv2*

ADD Cargo.toml .
ADD static ./static
ADD src ./src
RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release


FROM talk.schwanzer.online/dockerhub_proxy/library/alpine:latest
WORKDIR /app
RUN apk add libgcc tzdata
ENV TZ=Europe/Berlin

COPY --from=builder /app/src/target/release/podgrabv2 /app/podgrabv2
COPY --from=ui-builder /app/dist /app/static

EXPOSE 8000
CMD ["/app/podgrabv2"]