FROM node:latest as ui-builder

WORKDIR /app
COPY ./ui/ ./
RUN  npm install && npm run build


FROM library/alpine:3.17 as builder

USER root

WORKDIR /app/src

RUN apk add pkgconfig openssl-dev libc-dev curl

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

COPY --from=ui-builder /app/dist /app/src/static

ADD Cargo.toml .
ADD static ./static
ADD migrations ./migrations
ADD src ./src
RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release


FROM library/alpine:latest
WORKDIR /app/
RUN apk install libgcc tzdata
ENV TZ=Europe/Berlin

COPY --from=builder /app/src/target/release/podgrabv2 /app/podgrabv2
COPY --from=builder /app/src/migrations /app/migrations
COPY --from=ui-builder /app/dist /app/static

EXPOSE 8000
CMD ["./podgrabv2"]