# syntax = docker/dockerfile:experimental


FROM node:latest as ui-builder

WORKDIR /app
COPY ./ui/ ./
RUN  npm install && npm run build


FROM library/rust:1.68-slim-buster as builder

USER root

RUN apt update && apt install -y pkg-config libssl-dev libc-dev
WORKDIR /app/src

COPY --from=ui-builder /app/dist /app/src/static

ADD Cargo.lock .
ADD Cargo.toml .
ADD static ./static
ADD migrations ./migrations
ADD src ./src
RUN --security=insecure mkdir -p /root/.cargo && \
    chmod 777 /root/.cargo && \
    mount -t tmpfs none /root/.cargo && \
    cargo build --release
FROM library/ubuntu:latest
WORKDIR /app/


COPY --from=builder /app/src/target/release/podgrabv2 /app/podgrabv2
COPY --from=builder /app/src/migrations /app/migrations
COPY --from=ui-builder /app/dist /app/static

EXPOSE 8000
CMD ["./podgrabv2"]