FROM scratch

ARG FILE

WORKDIR /app/
COPY ./target/$FILE/release/podfetch /app/podfetch

COPY ./ui/dist /app/static
COPY ./migrations /app/migrations
COPY ./db /app/db
RUN ls

EXPOSE 8000
ENTRYPOINT ["./podfetch"]