FROM docker-registry.schwanzer.online/dockerhub_proxy/bash:4.4 as base
COPY ./ui/dist /app/static
COPY ./migrations /app/migrations
COPY ./db /app/db
WORKDIR /app/

FROM base as amd64
COPY ./target/x86_64-unknown-linux-gnu/release/podfetch /app/podfetch

FROM base as armv7
COPY ./target/armv7-unknown-linux-gnueabihf/release/podfetch /app/podfetch

FROM base as arm64
COPY ./target/aarch64-unknown-linux-gnu/release/podfetch /app/podfetch

FROM ${TARGETARCH}${TARGETVARIANT} as final
EXPOSE 8000
CMD ["./podfetch"]