# syntax = docker/dockerfile:experimental

FROM library/node:lts-bullseye as ui-builder

WORKDIR /app
COPY ./ui/ ./
RUN  npm install && npm run build


FROM alpine as dependency-cache
RUN apk add pkgconfig openssl-dev libc-dev git curl
RUN --security=insecure curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

USER root

WORKDIR /app/src
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

ADD Cargo.toml .
ADD dummy.rs ./src/main.rs
ADD build.rs .
RUN cargo update
RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release


FROM alpine as builder

RUN apk add pkgconfig openssl-dev libc-dev git curl

RUN --security=insecure curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
USER root

WORKDIR /app/src


ENV CARGO_NET_GIT_FETCH_WITH_CLI=true


COPY --from=dependency-cache /usr/local/cargo /usr/local/cargo
COPY --from=dependency-cache /app/src/target/ /app/src/target/
RUN rm -rf /app/src/static/*||true
COPY --from=ui-builder /app/dist /app/src/static
RUN rm -rf /app/src/target/release/deps/podfetch*
RUN rm -rf /app/src/target/release/podfetch*

ADD Cargo.toml .
ADD static ./static
ADD migrations ./migrations
ADD src ./src
ADD build.rs .
ADD db ./db
RUN cargo update
RUN --security=insecure mkdir -p /usr/local/cargo/registry/index && \
    chmod 777 /usr/local/cargo/registry/index && \
    mount -t tmpfs none /usr/local/cargo/registry/index && \
    RUSTFLAGS='-C target-feature=-crt-static' cargo build --release


FROM library/alpine:3.17 AS Runtime
WORKDIR /app/
RUN apk add libgcc tzdata
ENV TZ=Europe/Berlin

COPY --from=builder /app/src/target/release/podfetch /app/podfetch
COPY --from=builder /app/src/migrations /app/migrations
COPY --from=builder /app/src/db /app/db
COPY --from=ui-builder /app/dist /app/static
COPY ./docs/default.jpg /app/static/default.jpg


EXPOSE 8000
CMD ["./podfetch"]