FROM ubuntu:latest AS builder

RUN apt-get update && apt-get install libpq5 -y


FROM gcr.io/distroless/cc as base
COPY ./static/ /app/static
COPY ./migrations /app/migrations
COPY ./db /app/db
WORKDIR /app/

FROM base as amd64
ENV ARCH=x86_64-linux-gnu

COPY --from=builder /usr/lib/${ARCH}/libpq.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgssapi_krb5.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libldap_r-2.4.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libkrb5.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libk5crypto.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libkrb5support.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/liblber-2.4.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libsasl2.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgnutls.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libp11-kit.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libidn2.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libunistring.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libtasn1.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libnettle.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libhogweed.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgmp.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libffi.so* /usr/lib/${ARCH}/
COPY --from=builder /lib/${ARCH}/libcom_err.so* /lib/${ARCH}/
COPY --from=builder /lib/${ARCH}/libkeyutils.so* /lib/${ARCH}/

COPY /usr/lib/${ARCH}/libcrypto.so.1.1 /usr/lib/${ARCH}/libcrypto.so
COPY /usr/lib/${ARCH}/libssl.so.1.1 /usr/lib/${ARCH}/libssl.so

COPY ./target/x86_64-unknown-linux-gnu/release/podfetch /app/podfetch

FROM base as armv7
ENV ARCH=arm-linux-gnueabihf
COPY --from=builder /usr/lib/${ARCH}/libpq.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgssapi_krb5.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libldap_r-2.4.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libkrb5.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libk5crypto.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libkrb5support.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/liblber-2.4.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libsasl2.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgnutls.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libp11-kit.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libidn2.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libunistring.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libtasn1.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libnettle.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libhogweed.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgmp.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libffi.so* /usr/lib/${ARCH}/
COPY --from=builder /lib/${ARCH}/libcom_err.so* /lib/${ARCH}/
COPY --from=builder /lib/${ARCH}/libkeyutils.so* /lib/${ARCH}/

COPY /usr/lib/${ARCH}/libcrypto.so.1.1 /usr/lib/${ARCH}/libcrypto.so
COPY /usr/lib/${ARCH}/libssl.so.1.1 /usr/lib/${ARCH}/libssl.so

COPY ./target/armv7-unknown-linux-gnueabihf/release/podfetch /app/podfetch

FROM base as arm64
ENV ARCH=aarch64-linux-gnu

COPY --from=builder /usr/lib/${ARCH}/libpq.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgssapi_krb5.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libldap_r-2.4.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libkrb5.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libk5crypto.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libkrb5support.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/liblber-2.4.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libsasl2.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgnutls.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libp11-kit.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libidn2.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libunistring.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libtasn1.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libnettle.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libhogweed.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libgmp.so* /usr/lib/${ARCH}/
COPY --from=builder /usr/lib/${ARCH}/libffi.so* /usr/lib/${ARCH}/
COPY --from=builder /lib/${ARCH}/libcom_err.so* /lib/${ARCH}/
COPY --from=builder /lib/${ARCH}/libkeyutils.so* /lib/${ARCH}/

COPY /usr/lib/${ARCH}/libcrypto.so.1.1 /usr/lib/${ARCH}/libcrypto.so
COPY /usr/lib/${ARCH}/libssl.so.1.1 /usr/lib/${ARCH}/libssl.so

COPY ./target/aarch64-unknown-linux-gnu/release/podfetch /app/podfetch

FROM ${TARGETARCH}${TARGETVARIANT} as final


EXPOSE 8000
CMD ["./podfetch"]