import createClient, {Middleware} from "openapi-fetch";

export let apiURL: string
export let uiURL: string
if (window.location.pathname.startsWith("/ui")) {
    apiURL = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + "/api/v1"
} else {
    //match everything before /ui
    const regex = /\/([^/]+)\/ui\//
    apiURL = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + "/" + regex.exec(window.location.href)![1] + "/api/v1"
}
uiURL = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + "/ui"

import type { paths } from "../../schema";
import useCommon from "../store/CommonSlice"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: apiURL });

const authMiddleware: Middleware = {
    async onRequest({ request, options }) {
        const headers = useCommon.getState().headers
        Object.entries(headers).forEach(([key,val]) => {
            request.headers.set(key, val)
        })
        return request;
    }
};

client.use(authMiddleware)


client.GET("/api/v1/sys/config", {
    headers: {
        "Content-Type": "application/json"
    },
    asdamasld: {

    }
})
