import createClient, {Middleware} from "openapi-fetch";

export let apiURL: string
export let uiURL: string
if (window.location.pathname.startsWith("/ui")) {
    apiURL = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port
} else {
    //match everything before /ui
    const regex = /\/([^/]+)\/ui\//
    apiURL = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + "/" + regex.exec(window.location.href)![1]
}
uiURL = window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + "/ui"

import type { paths } from "../../schema";
import useCommon from "../store/CommonSlice"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: apiURL });

const authMiddleware: Middleware = {
    async onRequest({ request, options }) {
        const headers = useCommon.getState().headers
        if (sessionStorage.getItem("auth") !== null) {
            headers.Authorization = "Basic " + sessionStorage.getItem("auth")
        }
        Object.entries(headers).forEach(([key, value]) => {
            request.headers.set(key, value)
        })
        return request;
    },
    async onResponse({ response }) {

        if (!response.ok) {
            throw new Error("Request failed: " + response.body === null? response.statusText: await response.text() );
        }

        return response;
    },
};

client.use(authMiddleware)


client.GET("/api/v1/sys/config", {
    headers: {
        "Content-Type": "application/json"
    },
    asdamasld: {

    }
})
