//! JSON-over-WebSocket protocol shared between a PodFetch server and a
//! `--agent` instance running on the user's home LAN.
//!
//! Messages are exchanged as text frames. Both directions use the same
//! framing — an envelope with a `kind` discriminant and an optional
//! `request_id` for correlated request/response pairs (e.g. `Play` →
//! `SessionStarted`).
//!
//! The protocol is versioned via [`PROTOCOL_VERSION`]; both peers report
//! their version in the initial Hello/HelloAck exchange and refuse to
//! continue if they're incompatible.

use podfetch_cast::{
    CastSessionId, CastStatus, ControlCmd, DiscoveredCastDevice,
};
use serde::{Deserialize, Serialize};

/// Bumped whenever a wire-incompatible change lands.
pub const PROTOCOL_VERSION: u32 = 1;

/// Identifier for a request waiting on a correlated reply. Generated by the
/// peer issuing the request; the responder echoes it verbatim.
pub type RequestId = String;

// ── Server → Agent ──────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ServerMsg {
    /// Sent right after the websocket upgrade. The agent must respond with
    /// `HelloAck` before any other traffic is accepted.
    Hello {
        protocol_version: u32,
        server_version: String,
    },
    /// Ask the agent to run a fresh mDNS discovery scan and report back via
    /// `DeviceList`.
    DiscoverRequest {
        request_id: RequestId,
    },
    /// Start media playback on a given device. The agent replies with
    /// `SessionStarted { request_id, session_id }` on success or
    /// `Error { request_id, ... }` on failure.
    Play {
        request_id: RequestId,
        chromecast_uuid: String,
        media: PlayMedia,
    },
    /// Issue a control command against an active session.
    Control {
        request_id: RequestId,
        session_id: CastSessionId,
        cmd: ControlCmd,
    },
    /// Polite shutdown — the server is going away, the agent should close
    /// after acknowledging in-flight work.
    Goodbye,
    /// Liveness probe; agent must reply with [`AgentMsg::Pong`].
    Ping,
}

/// Subset of [`podfetch_cast::CastMedia`] that crosses the wire — IpAddr
/// and other internal types are kept on the orchestrator side.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct PlayMedia {
    pub url: String,
    pub mime: String,
    pub title: String,
    pub artwork_url: Option<String>,
    pub duration_secs: Option<f64>,
    pub episode_id: Option<i32>,
}

// ── Agent → Server ──────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum AgentMsg {
    HelloAck {
        protocol_version: u32,
        agent_id: String,
        agent_version: String,
        capabilities: AgentCapabilities,
    },
    /// Snapshot of every CAST device the agent currently sees on its LAN.
    /// Sent unsolicited whenever the device set changes, and as a reply to
    /// a `DiscoverRequest`. `request_id` echoes the request when this is a
    /// reply, otherwise `None`.
    DeviceList {
        request_id: Option<RequestId>,
        devices: Vec<DiscoveredCastDevice>,
    },
    /// Reply to `Play` — the session id the agent assigned.
    SessionStarted {
        request_id: RequestId,
        session_id: CastSessionId,
    },
    /// Streamed status update for an active session.
    Status {
        status: CastStatus,
    },
    /// Session has terminated naturally or due to error.
    SessionEnded {
        session_id: CastSessionId,
        reason: SessionEndReason,
    },
    /// Reply for any failed correlated request.
    Error {
        request_id: Option<RequestId>,
        code: ErrorCode,
        message: String,
    },
    Pong,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct AgentCapabilities {
    /// True if this agent can speak the local CAST protocol. (Always `true`
    /// in v1 — kept as a field so future backends like AirPlay can be
    /// negotiated without a protocol bump.)
    pub chromecast: bool,
    /// True if the agent is willing to act as a local HTTP proxy that
    /// re-serves episode bytes pulled from the server. Required for the
    /// public-instance scenario where the Chromecast can't reach the server
    /// directly.
    pub local_proxy: bool,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SessionEndReason {
    Stopped,
    Finished,
    DeviceGone,
    Error,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    DeviceNotFound,
    SessionNotFound,
    Receiver,
    Transport,
    NotImplemented,
    InvalidRequest,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip<T>(value: &T)
    where
        T: Serialize + for<'a> Deserialize<'a> + std::fmt::Debug + PartialEq,
    {
        let json = serde_json::to_string(value).expect("serialize");
        let parsed: T = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(*value, parsed);
    }

    #[test]
    fn server_messages_round_trip() {
        round_trip(&ServerMsg::Hello {
            protocol_version: PROTOCOL_VERSION,
            server_version: "0.1.0".into(),
        });
        round_trip(&ServerMsg::DiscoverRequest {
            request_id: "req-1".into(),
        });
        round_trip(&ServerMsg::Play {
            request_id: "req-2".into(),
            chromecast_uuid: "uuid-1".into(),
            media: PlayMedia {
                url: "https://x/audio.mp3".into(),
                mime: "audio/mpeg".into(),
                title: "Episode 1".into(),
                artwork_url: None,
                duration_secs: Some(1800.0),
                episode_id: Some(42),
            },
        });
        round_trip(&ServerMsg::Goodbye);
        round_trip(&ServerMsg::Ping);
    }

    #[test]
    fn agent_messages_round_trip() {
        round_trip(&AgentMsg::HelloAck {
            protocol_version: PROTOCOL_VERSION,
            agent_id: "agent-uuid".into(),
            agent_version: "0.1.0".into(),
            capabilities: AgentCapabilities {
                chromecast: true,
                local_proxy: true,
            },
        });
        round_trip(&AgentMsg::DeviceList {
            request_id: Some("req-1".into()),
            devices: vec![],
        });
        round_trip(&AgentMsg::Pong);
        round_trip(&AgentMsg::Error {
            request_id: Some("req-3".into()),
            code: ErrorCode::DeviceNotFound,
            message: "no such device".into(),
        });
    }

    #[test]
    fn server_msg_uses_kind_tag() {
        let msg = ServerMsg::Ping;
        let json = serde_json::to_value(msg).unwrap();
        assert_eq!(json["kind"], "ping");
    }
}
