export type PodcastSetting = {
    podcastId: string,
    episodeNumbering: boolean,
    autoDownload: boolean,
    autoUpdate: boolean,
    autoCleanup: boolean,
    autoCleanupDays: number,
    replaceInvalidCharacters: boolean,
    useExistingFilename: boolean,
    replacementStrategy: string,
    episodeFormat: string,
    podcastFormat: string,
    directPaths: boolean,
    activated: boolean,
    podcastPrefill: number,
    useOneCoverForAllEpisodes: boolean,
    nfoFormat: string,
    coverFilename: string,
}
