export type Setting = {
    id: string,
    episodeNumbering: boolean,
    autoDownload: boolean,
    autoUpdate: boolean,
    autoCleanup: boolean,
    autoCleanupDays: number,
    podcastPrefill: number,
    useExistingFilename: boolean,
    replaceInvalidCharacters: boolean,
    replacementStrategy: string,
    episodeFormat: string,
    podcastFormat: string,
    directPaths: boolean,
    autoTranscodeOpus: boolean,
    useOneCoverForAllEpisodes: boolean,
    nfoFormat: string,
    coverFilename: string,
    maxParallelDownloads: number,
}
